[build]
  publish = "public"
  functions = "netlify/functions"

[[snippets]]
  location = "head"
  contents = "<meta name='wt-cfg' content='REPLACE_KEY_HERE'>"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
